version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - clinica-network

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - MYSQL_REMOTE_HOST=${MYSQL_REMOTE_HOST}
      - MYSQL_REMOTE_USER=${MYSQL_REMOTE_USER}
      - MYSQL_REMOTE_PASSWORD=${MYSQL_REMOTE_PASSWORD}
      - MYSQL_REMOTE_DATABASE=${MYSQL_REMOTE_DATABASE}
    restart: unless-stopped
    networks:
      - clinica-network
    volumes:
      - .:/app
      - backend_data:/app/data

volumes:
  backend_data:

networks:
  clinica-network:
    driver: bridge
